#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// A simple node structure for our static tree
struct Node {
    char data;
    struct Node *left, *right;
};

// Helper function to create a new tree node
struct Node* createNode(char data) {
    struct Node* node = (struct Node*)malloc(sizeof(struct Node));
    node->data = data;
    node->left = NULL;
    node->right = NULL;
    return node;
}

// Manually builds the exact Huffman Tree generated by your program for "banana"
struct Node* buildStaticBananaTree() {
    // 1. Create the character leaf nodes
    struct Node* leafA = createNode('a');
    struct Node* leafB = createNode('b');
    struct Node* leafN = createNode('n');

    // 2. Combine 'b' and 'n' under an internal parent node '$'
    struct Node* internalSubTree = createNode('$');
    internalSubTree->left = leafB;   // Left branch path = 0 (makes 'b' -> 10)
    internalSubTree->right = leafN;  // Right branch path = 1 (makes 'n' -> 11)

    // 3. Combine 'a' and the sub-tree under the ultimate root node '$'
    struct Node* root = createNode('$');
    root->left = leafA;              // Left branch path = 0 (makes 'a' -> 0)
    root->right = internalSubTree;   // Right branch path = 1

    return root;
}

// Decodes the hardcoded binary stream back into text
void decodeBanana(struct Node* root, const char* bitstream) {
    struct Node* current = root;
    
    printf("Decoded Output: ");
    for (int i = 0; bitstream[i] != '\0'; i++) {
        // Move down the branches based on the bit character
        if (bitstream[i] == '0') {
            current = current->left;
        } else if (bitstream[i] == '1') {
            current = current->right;
        }

        // If a leaf node is hit, print the character and snap back to the root
        if (current->left == NULL && current->right == NULL) {
            printf("%c", current->data);
            current = root; 
        }
    }
    printf("\n");
}

int main() {
    // The exact hardcoded bitstream output your program produces for "banana"
    const char* encodedBanana = "100110110"; 
    
    printf("--- Hardcoded Banana Huffman Demonstration ---\n");
    printf("Character Dictionary Mapping:\n");
    printf("a: 0\n");
    printf("b: 10\n");
    printf("n: 11\n\n");
    
    printf("Encoded Bitstream: %s\n", encodedBanana);

    // Build the static architectural framework
    struct Node* root = buildStaticBananaTree();

    // Execute the traversal decoding engine
    decodeBanana(root, encodedBanana);

    return 0;
}
